//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinMessaging.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinMessaging.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ABOUT.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to contacts.
        /// </summary>
        public static string AddContacts {
            get {
                return ResourceManager.GetString("AddContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à APPLICATION.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You acquire the Geek badge when you are testing PinMessaging for us!.
        /// </summary>
        public static string BadgeBetatester {
            get {
                return ResourceManager.GetString("BadgeBetatester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You acquire the Diplomat badge when you comment 50 times. Keep going!.
        /// </summary>
        public static string BadgeComments50 {
            get {
                return ResourceManager.GetString("BadgeComments50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No badge yet. Badges can be acquired by creating and commenting pins.
        /// </summary>
        public static string BadgeNoBadge {
            get {
                return ResourceManager.GetString("BadgeNoBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You acquire the Conqueror badge when you create 50 pins. Keep going!.
        /// </summary>
        public static string BadgePin50 {
            get {
                return ResourceManager.GetString("BadgePin50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You acquire the Newbie badge when you get between 0 and 50 points. Keep going!.
        /// </summary>
        public static string BadgePointCopper {
            get {
                return ResourceManager.GetString("BadgePointCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You acquire the Explorer badge when you get more than 500 points. Good job!.
        /// </summary>
        public static string BadgePointGold {
            get {
                return ResourceManager.GetString("BadgePointGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You acquire Adventurer badge when you get between 50 and 500 points. Keep going! The gold is not far!.
        /// </summary>
        public static string BadgePointSilver {
            get {
                return ResourceManager.GetString("BadgePointSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BADGES.
        /// </summary>
        public static string BadgesTitle {
            get {
                return ResourceManager.GetString("BadgesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à best badge.
        /// </summary>
        public static string BestBadgeTitle {
            get {
                return ResourceManager.GetString("BestBadgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection.
        /// </summary>
        public static string ButtonConnection {
            get {
                return ResourceManager.GetString("ButtonConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Account.
        /// </summary>
        public static string ButtonCreateAccount {
            get {
                return ResourceManager.GetString("ButtonCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string ButtonValidate {
            get {
                return ResourceManager.GetString("ButtonValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing the language will reload PinMessaging.
        /// </summary>
        public static string ChangeLanguageWarning {
            get {
                return ResourceManager.GetString("ChangeLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Password.
        /// </summary>
        public static string ChangePwd {
            get {
                return ResourceManager.GetString("ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password could not be changed.
        /// </summary>
        public static string ChangePwdError {
            get {
                return ResourceManager.GetString("ChangePwdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password was changed successfully!.
        /// </summary>
        public static string ChangePwdSuccess {
            get {
                return ResourceManager.GetString("ChangePwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm your password.
        /// </summary>
        public static string ConfirmPwd {
            get {
                return ResourceManager.GetString("ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEARCH.
        /// </summary>
        public static string ContactSearch {
            get {
                return ResourceManager.GetString("ContactSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MY CONTACTS.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Account.
        /// </summary>
        public static string CreateAccountPageTitle {
            get {
                return ResourceManager.GetString("CreateAccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a description for your Pin.
        /// </summary>
        public static string CreatePinDescription {
            get {
                return ResourceManager.GetString("CreatePinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title of your Pin.
        /// </summary>
        public static string CreatePinDescriptionTitle {
            get {
                return ResourceManager.GetString("CreatePinDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à create pin.
        /// </summary>
        public static string CreatePinTitle {
            get {
                return ResourceManager.GetString("CreatePinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à event date and time.
        /// </summary>
        public static string EventDateTimeTitle {
            get {
                return ResourceManager.GetString("EventDateTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FAVORITE PINS.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You found a bug, have a suggestion or a question? That&apos;s here!.
        /// </summary>
        public static string FeedbackTip {
            get {
                return ResourceManager.GetString("FeedbackTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à filter.
        /// </summary>
        public static string FilterPageTitle {
            get {
                return ResourceManager.GetString("FilterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geek.
        /// </summary>
        public static string GradeBetaTester {
            get {
                return ResourceManager.GetString("GradeBetaTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diplomat.
        /// </summary>
        public static string GradeMessage50 {
            get {
                return ResourceManager.GetString("GradeMessage50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No grade yet.
        /// </summary>
        public static string GradeNoGrade {
            get {
                return ResourceManager.GetString("GradeNoGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conqueror.
        /// </summary>
        public static string GradePin50 {
            get {
                return ResourceManager.GetString("GradePin50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Newbie.
        /// </summary>
        public static string GradePointCopper {
            get {
                return ResourceManager.GetString("GradePointCopper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explorer.
        /// </summary>
        public static string GradePointGold {
            get {
                return ResourceManager.GetString("GradePointGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adventurer.
        /// </summary>
        public static string GradePointSilver {
            get {
                return ResourceManager.GetString("GradePointSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à grade.
        /// </summary>
        public static string GradeTitle {
            get {
                return ResourceManager.GetString("GradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you already have an account?.
        /// </summary>
        public static string HaveAccountOrNot {
            get {
                return ResourceManager.GetString("HaveAccountOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HISTORY.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New favorite.
        /// </summary>
        public static string HistoryAddFavoriteLocation {
            get {
                return ResourceManager.GetString("HistoryAddFavoriteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New favorite.
        /// </summary>
        public static string HistoryAddFavoriteUser {
            get {
                return ResourceManager.GetString("HistoryAddFavoriteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin modified.
        /// </summary>
        public static string HistoryChangePin {
            get {
                return ResourceManager.GetString("HistoryChangePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New comment.
        /// </summary>
        public static string HistoryCommentPin {
            get {
                return ResourceManager.GetString("HistoryCommentPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin created.
        /// </summary>
        public static string HistoryCreatePin {
            get {
                return ResourceManager.GetString("HistoryCreatePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin deleted.
        /// </summary>
        public static string HistoryDeletePin {
            get {
                return ResourceManager.GetString("HistoryDeletePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on PinMessaging!.
        /// </summary>
        public static string HistoryNewUser {
            get {
                return ResourceManager.GetString("HistoryNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        public static string LeftMenuTitle {
            get {
                return ResourceManager.GetString("LeftMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LEGAL.
        /// </summary>
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localize.
        /// </summary>
        public static string Localize {
            get {
                return ResourceManager.GetString("Localize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location services.
        /// </summary>
        public static string LocationServices {
            get {
                return ResourceManager.GetString("LocationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure to logout?.
        /// </summary>
        public static string LogoutSentence {
            get {
                return ResourceManager.GetString("LogoutSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters.
        /// </summary>
        public static string MenuFilters {
            get {
                return ResourceManager.GetString("MenuFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map.
        /// </summary>
        public static string MenuMap {
            get {
                return ResourceManager.GetString("MenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My pins.
        /// </summary>
        public static string MenuPins {
            get {
                return ResourceManager.GetString("MenuPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My profil.
        /// </summary>
        public static string MenuProfil {
            get {
                return ResourceManager.GetString("MenuProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rewards.
        /// </summary>
        public static string MenurRewards {
            get {
                return ResourceManager.GetString("MenurRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Pins.
        /// </summary>
        public static string MyPins {
            get {
                return ResourceManager.GetString("MyPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MY PINS.
        /// </summary>
        public static string MyPinsPivot {
            get {
                return ResourceManager.GetString("MyPinsPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please check your connection and try again.
        /// </summary>
        public static string NetworkProblem {
            get {
                return ResourceManager.GetString("NetworkProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We cannot connect you to our services. Would you like to use the application offline?.
        /// </summary>
        public static string NetworkProblemServer {
            get {
                return ResourceManager.GetString("NetworkProblemServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New email address.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password.
        /// </summary>
        public static string NewPwd {
            get {
                return ResourceManager.GetString("NewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à notification.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number of comments posted.
        /// </summary>
        public static string NumCommentsCreated {
            get {
                return ResourceManager.GetString("NumCommentsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à number of pins created.
        /// </summary>
        public static string NumPinsCreated {
            get {
                return ResourceManager.GetString("NumPinsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not connected.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old password.
        /// </summary>
        public static string OldPwd {
            get {
                return ResourceManager.GetString("OldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à author.
        /// </summary>
        public static string PinAuthor {
            get {
                return ResourceManager.GetString("PinAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chose receipients.
        /// </summary>
        public static string PinCreateReceiver {
            get {
                return ResourceManager.GetString("PinCreateReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on the Pins underneath to display or hide them on the map.
        /// </summary>
        public static string PinDisplayedInfos {
            get {
                return ResourceManager.GetString("PinDisplayedInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMAGE.
        /// </summary>
        public static string PinImage {
            get {
                return ResourceManager.GetString("PinImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last step.
        /// </summary>
        public static string PinLastStep {
            get {
                return ResourceManager.GetString("PinLastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copyright 2014, PinMessaging Corporation. All right reserved..
        /// </summary>
        public static string PinMessagingCopyright {
            get {
                return ResourceManager.GetString("PinMessagingCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;application PinMessaging est une application Smartphone qui permet à ses utilisateurs de poster des messages à leur emplacement géographique. Les messages sont rattachés à un endroit, donc pour pouvoir les lire, l&apos;utilisateur devra se trouver au même emplacement. Ces messages pourront être de simples commentaires sur un endroit, des remarques ou des astuces.
        ///Le même principe de messages géolocalisés est appliqué pour les évènements, comme par exemple pour un festival costumé ou un concert.
        ///PinMessaging  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string PinMessagingInfos {
            get {
                return ResourceManager.GetString("PinMessagingInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version: 1.0.0.
        /// </summary>
        public static string PinMessagingVersion {
            get {
                return ResourceManager.GetString("PinMessagingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PinMessaging for Windows Phone.
        /// </summary>
        public static string PinMessagingWP {
            get {
                return ResourceManager.GetString("PinMessagingWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à private event.
        /// </summary>
        public static string PinPrivateEvent {
            get {
                return ResourceManager.GetString("PinPrivateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à private message.
        /// </summary>
        public static string PinPrivateMessage {
            get {
                return ResourceManager.GetString("PinPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à private point of interest.
        /// </summary>
        public static string PinPrivatePointOfInterest {
            get {
                return ResourceManager.GetString("PinPrivatePointOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à private point of vue.
        /// </summary>
        public static string PinPrivatePointOfView {
            get {
                return ResourceManager.GetString("PinPrivatePointOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public event.
        /// </summary>
        public static string PinPublicEvent {
            get {
                return ResourceManager.GetString("PinPublicEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public message.
        /// </summary>
        public static string PinPublicMessage {
            get {
                return ResourceManager.GetString("PinPublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public point of interest.
        /// </summary>
        public static string PinPublicPointOfInterest {
            get {
                return ResourceManager.GetString("PinPublicPointOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à public point of view.
        /// </summary>
        public static string PinPublicPointOfView {
            get {
                return ResourceManager.GetString("PinPublicPointOfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pins.
        /// </summary>
        public static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pins displayed on the map.
        /// </summary>
        public static string PinsDisplayed {
            get {
                return ResourceManager.GetString("PinsDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pins hidden on the map.
        /// </summary>
        public static string PinsNotDisplayed {
            get {
                return ResourceManager.GetString("PinsNotDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TITLE.
        /// </summary>
        public static string PinTitle {
            get {
                return ResourceManager.GetString("PinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password is incorrect.
        /// </summary>
        public static string PMConnectionFailUser {
            get {
                return ResourceManager.GetString("PMConnectionFailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create your password.
        /// </summary>
        public static string PMCreatePassword {
            get {
                return ResourceManager.GetString("PMCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your email.
        /// </summary>
        public static string PMEmail {
            get {
                return ResourceManager.GetString("PMEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The email already exists.
        /// </summary>
        public static string PMEmailAlreadyExists {
            get {
                return ResourceManager.GetString("PMEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The email does not exist.
        /// </summary>
        public static string PMEmailDoesNotExist {
            get {
                return ResourceManager.GetString("PMEmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your password.
        /// </summary>
        public static string PMPassword {
            get {
                return ResourceManager.GetString("PMPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The passwords are not the same.
        /// </summary>
        public static string PMPasswordsNotSame {
            get {
                return ResourceManager.GetString("PMPasswordsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retype password.
        /// </summary>
        public static string PMRetypePassword {
            get {
                return ResourceManager.GetString("PMRetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something went wrong. Please try again later.
        /// </summary>
        public static string PMSignUpError {
            get {
                return ResourceManager.GetString("PMSignUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The email address in incorrectly formated.
        /// </summary>
        public static string PMWrongEmailSyntax {
            get {
                return ResourceManager.GetString("PMWrongEmailSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password must contain between 6 and 20 characters .
        /// </summary>
        public static string PMWrongPasswordSyntax {
            get {
                return ResourceManager.GetString("PMWrongPasswordSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à points.
        /// </summary>
        public static string PointsTitle {
            get {
                return ResourceManager.GetString("PointsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Private message.
        /// </summary>
        public static string PrivateMessage {
            get {
                return ResourceManager.GetString("PrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à profil details.
        /// </summary>
        public static string ProfilDetailsTitle {
            get {
                return ResourceManager.GetString("ProfilDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PROFIL.
        /// </summary>
        public static string ProfilTitle {
            get {
                return ResourceManager.GetString("ProfilTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure to quit the application?.
        /// </summary>
        public static string QuitApp {
            get {
                return ResourceManager.GetString("QuitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string QuitAppTitle {
            get {
                return ResourceManager.GetString("QuitAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à refresh pins.
        /// </summary>
        public static string RefreshPins {
            get {
                return ResourceManager.GetString("RefreshPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See on map.
        /// </summary>
        public static string SeeOnMap {
            get {
                return ResourceManager.GetString("SeeOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share a pin.
        /// </summary>
        public static string SharePin {
            get {
                return ResourceManager.GetString("SharePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in.
        /// </summary>
        public static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STATS.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks for your participation :).
        /// </summary>
        public static string ThanksFeedback {
            get {
                return ResourceManager.GetString("ThanksFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unfriend.
        /// </summary>
        public static string Unfriend {
            get {
                return ResourceManager.GetString("Unfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sharing this information helps us provide and improve the location-based services offered for this phone. We won&apos;t use the information to identify or contact you..
        /// </summary>
        public static string UseLocationContent {
            get {
                return ResourceManager.GetString("UseLocationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow this application to access and use your location?.
        /// </summary>
        public static string UseLocationTitle {
            get {
                return ResourceManager.GetString("UseLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on PinMessaging, the new geolocated social application!.
        /// </summary>
        public static string WelcomeSentence {
            get {
                return ResourceManager.GetString("WelcomeSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à you.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
